table Dim_Product
	lineageTag: c6c18f02-5ad0-4008-b275-f25685c7ccf9

	column Product_Family
		dataType: string
		lineageTag: 909c68a1-b0c4-4969-b39a-33809b2e2a84
		summarizeBy: none
		sourceColumn: Product_Family

		annotation SummarizationSetBy = Automatic

	column Product_Family_Id
		dataType: int64
		formatString: 0
		lineageTag: 0cc62ba5-b478-4c4c-9d85-8963f5cfcd8c
		summarizeBy: none
		sourceColumn: Product_Family_Id

		annotation SummarizationSetBy = Automatic

	column Product_Group
		dataType: string
		lineageTag: 17e9fda4-76f7-4125-b607-1c01420b0d55
		summarizeBy: none
		sourceColumn: Product_Group

		annotation SummarizationSetBy = Automatic

	column Product_Group_id
		dataType: int64
		formatString: 0
		lineageTag: 1c5db2ec-f0cb-4fc0-af3e-cb8803675707
		summarizeBy: none
		sourceColumn: Product_Group_id

		annotation SummarizationSetBy = Automatic

	column Product_Name
		dataType: string
		lineageTag: 648280ab-bdcf-4cca-8354-96e488718e81
		summarizeBy: none
		sourceColumn: Product_Name

		annotation SummarizationSetBy = Automatic

	column Product_Name_id
		dataType: int64
		formatString: 0
		lineageTag: 2f450166-a08c-47c2-aaa1-99c4553368a1
		summarizeBy: none
		sourceColumn: Product_Name_id

		annotation SummarizationSetBy = Automatic

	column Product_Size
		dataType: string
		lineageTag: fefcee19-ad25-4d8d-a749-e5180466560f
		summarizeBy: none
		sourceColumn: Product_Size

		annotation SummarizationSetBy = Automatic

	column Produt_Type
		dataType: string
		lineageTag: 7b36110f-43fc-4f18-88c3-fcaa6684383a
		summarizeBy: none
		sourceColumn: Produt_Type

		annotation SummarizationSetBy = Automatic

	partition Dim_Product = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\nthom\OneDrive\Documents\Power BI Projects\Portfolio Project\Plant_DTS.xls"), null, true),
				    Plant_Hierarchy1 = Source{[Name="Plant_Hierarchy"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Plant_Hierarchy1, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Product_Family", type text}, {"Product_Family_Id", Int64.Type}, {"Product_Group", type text}, {"Product_Group_id", Int64.Type}, {"Product_Name", type text}, {"Product_Name_id", Int64.Type}, {"Product_Size", type text}, {"Produt_Type", type text}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"Product_Name_id"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

