table Fact_Sales
	lineageTag: f1aa7640-e9e0-4d07-bb09-621bf651d8ec

	column Product_id
		dataType: int64
		formatString: 0
		lineageTag: a5576a9d-651a-4771-822f-7ae99180caf6
		summarizeBy: none
		sourceColumn: Product_id

		annotation SummarizationSetBy = Automatic

	column Sales_USD
		dataType: double
		lineageTag: a9b49fa8-c298-4232-95ee-e1d18941074c
		summarizeBy: sum
		sourceColumn: Sales_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column quantity
		dataType: double
		lineageTag: 7061cd7f-c5ae-473d-b8c0-b32c1d164c6a
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Price_USD
		dataType: double
		lineageTag: c3824690-b214-4ffd-8db3-4e4b35fad007
		summarizeBy: sum
		sourceColumn: Price_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COGS_USD
		dataType: double
		lineageTag: f58fffa0-f056-41c8-adec-116e0a59c609
		summarizeBy: sum
		sourceColumn: COGS_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date_Time
		dataType: dateTime
		formatString: Long Date
		lineageTag: a3db5866-47d1-4ae2-9473-9b5e4dd9c599
		summarizeBy: none
		sourceColumn: Date_Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Account_id
		dataType: string
		lineageTag: 62fdfa21-0dc5-467f-aeef-c4a1a24e2dbc
		summarizeBy: none
		sourceColumn: Account_id

		annotation SummarizationSetBy = Automatic

	partition Fact_Sales = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\nthom\OneDrive\Documents\Power BI Projects\Portfolio Project\Plant_DTS.xls"), null, true),
				    Plant_FACT1 = Source{[Name="Plant_FACT"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Plant_FACT1, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Product_id", Int64.Type}, {"Sales_USD", type number}, {"quantity", type number}, {"Price_USD", type number}, {"COGS_USD", type number}, {"Date_Time", type date}, {"Account_id", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

