table Design
	lineageTag: 7eac402b-9c7d-4a49-b8c3-506011c2d76b

	column Design
		dataType: string
		lineageTag: 1ba83d84-749c-4628-994b-d74a36451a4a
		summarizeBy: none
		sourceColumn: Design

		annotation SummarizationSetBy = Automatic

	column Acceptance
		dataType: string
		lineageTag: 70b4a25c-75f3-4006-b873-a59c21e30e07
		summarizeBy: none
		sourceColumn: Acceptance

		annotation SummarizationSetBy = Automatic

	column DesignID
		dataType: int64
		formatString: 0
		lineageTag: 19de83c5-e419-45ca-8075-aaaf46beda23
		summarizeBy: none
		sourceColumn: DesignID

		annotation SummarizationSetBy = Automatic

	partition Design = m
		mode: import
		source =
				let
				    Source = Construction,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Design", "Acceptance"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 400, 40, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "DesignID"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

